apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: default
  labels:
    app: todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: calamarzo/todoapp:latest
        env:
          - name: NODE_ENV
            value: prod
          - name: PORT
            value: "3000"
        ports:
        - containerPort: 3000
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
  name: todo-app-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: todo-app
  type: LoadBalancer 
